#!/bin/bash
. "/nfs/apps/test/conda_test/etc/profile.d/conda.sh"
conda activate /lab/solexa_page/hannah/mpraflow/MPRAflow/conda-env/MPRAflow
cd /lab/solexa_page/hannah/mpraflow/MPRAflow
nextflow run association_HH_edit.nf -w /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021 --fastq-insert "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/AAGAAGTTCA-s_2_cat_sequence.txt.gz" --fastq-insertPE "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/AAGAAGTTCA-s_1_cat_sequence.txt.gz" --fastq-bc "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/AAGAAGTTCA-s_3_cat_sequence.txt.gz" --design "/lab/solexa_page/hannah/lib_mpra/lib_mpra_ordered2.fa" --name assoc_basic  --outdir /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/AAGAAGTTCA
nextflow run association_HH_edit.nf -w /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021 --fastq-insert "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/AGCAAGTAGT-s_2_cat_sequence.txt.gz" --fastq-insertPE "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/AGCAAGTAGT-s_1_cat_sequence.txt.gz" --fastq-bc "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/AGCAAGTAGT-s_3_cat_sequence.txt.gz" --design "/lab/solexa_page/hannah/lib_mpra/lib_mpra_ordered2.fa" --name assoc_basic  --outdir /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/AGCAAGTAGT
nextflow run association_HH_edit.nf -w /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021 --fastq-insert "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/CGGCGCTGGC-s_2_cat_sequence.txt.gz" --fastq-insertPE "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/CGGCGCTGGC-s_1_cat_sequence.txt.gz" --fastq-bc "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/CGGCGCTGGC-s_3_cat_sequence.txt.gz" --design "/lab/solexa_page/hannah/lib_mpra/lib_mpra_ordered2.fa" --name assoc_basic  --outdir /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/CGGCGCTGGC
nextflow run association_HH_edit.nf -w /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021 --fastq-insert "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/TCGTCAACTT-s_2_cat_sequence.txt.gz" --fastq-insertPE "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/TCGTCAACTT-s_1_cat_sequence.txt.gz" --fastq-bc "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/TCGTCAACTT-s_3_cat_sequence.txt.gz" --design "/lab/solexa_page/hannah/lib_mpra/lib_mpra_ordered2.fa" --name assoc_basic  --outdir /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/TCGTCAACTT
nextflow run association_HH_edit.nf -w /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021 --fastq-insert "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/TGGTCTACGT-s_2_cat_sequence.txt.gz" --fastq-insertPE "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/TGGTCTACGT-s_1_cat_sequence.txt.gz" --fastq-bc "/lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/210909_WIGTC-HISEQ3B_HMHK3BCX3/QualityScore/TGGTCTACGT-s_3_cat_sequence.txt.gz" --design "/lab/solexa_page/hannah/lib_mpra/lib_mpra_ordered2.fa" --name assoc_basic  --outdir /lab/solexa_page/hannah/lib_mpra/mpra_assoc_sept2021/TGGTCTACGT


