import os 
import subprocess 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/NLGN4X") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/NLGN4Y") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/TXLNG") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/TXLNGY") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/EIF1AX") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/EIF1AY") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/KDM5D") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/KDM5C") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/UTY") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/KDM6A") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/ZFY") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/ZFX") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/DDX3Y") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/DDX3X") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/USP9Y") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/USP9X") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/RPS4Y1") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/RPS4X") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/TMSB4X") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
os.chdir("/lab/solexa_page/hannah/220516_mpra/msa/long_alignments/multiz_7sp/TMSB4Y") 
subprocess.run(["RepeatMasker", "-noint", "-species", "primates", "human"],  stderr=subprocess.PIPE) 
