---
title: "R Notebook"
output: html_notebook
---
https://zenodo.org/records/3627233 
```{r}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(broom) 

load("/lab/solexa_page/hannah/gtex_alex_MR/gtex.godfrey2020.ksto.gen24c.genes.tximport.RData")
abund <- txi.gtex.gn$abundance

abund <- as.data.frame(abund)

metadata <- read.delim("/lab/solexa_page/hannah/gtex_alex_MR/gtex_metadata.godfrey2020_simplified.txt")

metadata_xy <- metadata %>% filter(SEX == "male")

metadata_xy <- metadata_xy %>% filter(TISSUE != 'Testis' & 
                                        TISSUE != 'Prostate')

xypairs = c("EIF1AY","EIF1AX", "ZFX",  "ZFY", "USP9X", "USP9Y","DDX3X","DDX3Y","KDM6A", "UTY", "KDM5C", "KDM5D", "RPS4X", "RPS4Y1", "TXLNGY", "TMSB4Y", "NLGN4Y", "PRKY", 
"TBL1Y", "AMELY", "TSPY", "RBMY", "SRY", "HSFY")

abund_x <- abund %>% filter(rownames(abund) %in% xypairs)
abund_x <- as.data.frame(t(as.matrix(abund_x)))
abund_x <- abund_x %>% filter(rownames(abund_x) %in% metadata_xy$SAMPID) 

abund_x$SAMPID <- rownames(abund_x)

metadata_m <- merge(metadata_xy, abund_x, bt = "SAMPID")

```

```{r}

long_m <- metadata_m %>% pivot_longer(cols = c(9:22), names_to = "gene", values_to = "tpm")

```

#plot median
```{r}

med_lm <- unique(long_m %>% group_by(TISSUE, gene) %>% mutate("median" = median(tpm)) %>% select("gene", 'median', 'TISSUE'))

med_lm$color <- ifelse(med_lm$median < 1, "below", "above")

#pdf(file=("/lab/solexa_page/hannah/gtex_alex_MR/all_gtex_updown.pdf"), width=20, height=20, colormodel = "rgb")

med_lm %>% ggplot(aes(x=gene, y=median, color = color)) + 
  geom_jitter() +
  facet_wrap(~gene, scale = 'free') + 
  theme_pubr() 
#dev.off()

```


#GTEx LCL analysis 
```{r}






```






